#!/bin/bash
#
# Scans Submissions/ for ClipExperience conformances and generates SubmissionRegistry.swift.
# Added as an Xcode Run Script Build Phase so the registry updates every build.

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SUBMISSIONS_DIR="$ROOT_DIR/Submissions"
OUTPUT_FILE="$ROOT_DIR/ReactivChallengeKit/ReactivChallengeKit/SubmissionRegistry.swift"

TYPES=()

if [ -d "$SUBMISSIONS_DIR" ]; then
    while IFS= read -r line; do
        type_name="$(echo "$line" | sed -E 's/.*struct[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:.*/\1/')"
        if [ -n "$type_name" ]; then
            TYPES+=("$type_name")
        fi
    done < <(
        grep -r \
            --include="*.swift" \
            --exclude-dir="_template" \
            'struct[[:space:]]\+[A-Za-z0-9_]*[[:space:]]*:.*ClipExperience' \
            "$SUBMISSIONS_DIR" 2>/dev/null || true
    )
fi

# Keep deterministic output order and avoid duplicate entries.
if [ "${#TYPES[@]}" -gt 0 ]; then
    TYPES_SORTED=()
    while IFS= read -r type_name; do
        if [ -n "$type_name" ]; then
            TYPES_SORTED+=("$type_name")
        fi
    done < <(printf "%s\n" "${TYPES[@]}" | sort -u)
    TYPES=("${TYPES_SORTED[@]}")
fi

{
    echo "//  SubmissionRegistry.swift"
    echo "//  ReactivChallengeKit"
    echo "//"
    echo "//  Copyright © 2025 Reactiv Technologies Inc. All rights reserved."
    echo "//"
    echo ""
    echo "/// Auto-generated by scripts/generate-registry.sh — do not edit manually."
    echo "enum SubmissionRegistry {"
    echo "    static let all: [any ClipExperience.Type] = ["

    if [ "${#TYPES[@]}" -gt 0 ]; then
        for type in "${TYPES[@]}"; do
            echo "        ${type}.self,"
        done
    fi

    echo "    ]"
    echo "}"
} > "$OUTPUT_FILE"

echo "SubmissionRegistry: found ${#TYPES[@]} submission(s)"
